import { Lana } from "./lana";

const tiposDeLana = [ //creo un array con los tipos de lana
    "Lana Merino",
    "Lana de Alpaca",
    "Lana de Cachemira",
    "Lana Angora",
    "Lana de Mohair",
    "Lana de Yak",
    "Lana de Camello",
    "Lana de Llama",
    "Lana de Vicuña",
    "Lana de Guanaco",
    "Lana Corriedale",
    "Lana Lincoln",
    "Lana Romney",
    "Lana Hampshire",
    "Lana Leicester",
    "Lana Cotswold",
    "Lana Cheviot",
    "Lana Dorset",
    "Lana Suffolk",
    "Lana Oxford",
    "Lana Texel",
    "Lana Polwarth",
    "Lana Bluefaced Leicester",
    "Lana Gotland",
    "Lana Shetland",
    "Lana Icelandic",
    "Lana Norwegian",
    "Lana Finnsheep",
    "Lana Karakul",
    "Lana Navajo-Churro",
    "Lana Manx Loaghtan",
    "Lana Teeswater",
    "Lana Wensleydale",
    "Lana Black Welsh Mountain",
    "Lana Herdwick",
    "Lana Zwartbles",
    "Lana Clun Forest",
    "Lana Balwen",
    "Lana Hebridean",
    "Lana Soay",
    "Lana Jacob",
    "Lana Portland",
    "Lana Ryeland",
    "Lana Beulah",
    "Lana Exmoor Horn",
    "Lana Devon Closewool",
    "Lana Whiteface Woodland",
    "Lana Blue Texel",
    "Lana Valais Blacknose",
    "Lana Valais",
    "Lana Merino Superfina",
    "Lana Merino Extrafina",
    "Lana Merino Ultrafina",
    "Lana Merino Peinada",
    "Lana Merino Cardada",
    "Lana Merino Lavada",
    "Lana Merino Natural",
    "Lana Merino Rústica",
    "Lana Merino Suave",
    "Lana Merino Gruesa",
    "Lana de Alpaca Baby",
    "Lana de Alpaca Suri",
    "Lana de Alpaca Huacaya",
    "Lana de Alpaca Natural",
    "Lana de Alpaca Peinada",
    "Lana de Alpaca Cardada",
    "Lana de Mohair Kid",
    "Lana de Mohair Adulto",
    "Lana de Mohair Natural",
    "Lana de Mohair Peinada",
    "Lana de Cachemira Pura",
    "Lana de Cachemira Peinada",
    "Lana de Cachemira Cardada",
    "Lana de Cachemira Natural",
    "Lana de Angora Natural",
    "Lana de Angora Peinada",
    "Lana de Angora Cardada",
    "Lana de Yak Natural",
    "Lana de Yak Peinada",
    "Lana de Yak Cardada",
    "Lana de Camello Natural",
    "Lana de Camello Peinada",
    "Lana de Camello Cardada",
    "Lana de Llama Natural",
    "Lana de Llama Peinada",
    "Lana de Llama Cardada",
    "Lana de Vicuña Natural",
    "Lana de Vicuña Peinada",
    "Lana de Guanaco Natural",
    "Lana de Guanaco Peinada",
    "Lana Corriedale Natural",
    "Lana Corriedale Peinada",
    "Lana Corriedale Cardada",
    "Lana Lincoln Natural",
    "Lana Lincoln Peinada",
    "Lana Romney Natural",
    "Lana Romney Peinada",
    "Lana Shetland Natural",
    "Lana Shetland Peinada",
    "Lana Icelandic Natural",
    "Lana Icelandic Peinada"
];



const lanas: Lana[] = []; // Array para almacenar las instancias de Lana

for (const tipo of tiposDeLana) { 
    const lana = new Lana(tipo); 
    // Crea una instancia de Lana con el tipo de cada elemento del array tiposDeLana
    lanas.push(lana); // Agrega la instancia de Lana al array lanas
}